### ISSUE TITLE
Extension for token auto refresh

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-extensible#20]
Provide an extension to auto refresh the token.

**Comment by tylerlong** [comment]
Here is the C# version https://github.com/ringcentral/RingCentral.Net/tree/master/RingCentral.Net.AutoRefresh

**Comment by jeesus** [comment]
I have a prototype for TS, but I think the `TokenInfo` class would need additional property `expires_at` or smth since the `expires_in` has no use when carried over subsequent requests as it's relative to the time token was issued at.

**Comment by tylerlong** [comment]
@jeesus  I agree. However the TokenInfo class is auto generated base on swagger spec. You may need to sub-class it.

**Comment by tylerlong** [comment]
Done: https://github.com/ringcentral/ringcentral-extensible/tree/master/packages/extensions/auto-refresh
