### ISSUE TITLE
IE 11 error "use strict"

### ISSUE THREAD

**Issue by ruleechen** [ringcentral/ringcentral-extensible#22]
## Version
"@rc-ex/core": "^0.6.4"

## Console
![image_2021_3_10_13_5_2](https://user-images.githubusercontent.com/907369/110580090-e44f0100-81a2-11eb-8be6-22a396a05449.jpg)

**Comment by tylerlong** [comment]
What is the error message?

**Comment by tylerlong** [comment]
I doubt that it is IE 11 "use strict" issue. Because https://www.w3schools.com/js/js_strict.asp IE 10 already supports "use strict".

**Comment by tylerlong** [comment]
After lots of investigation, this is actually a genera issue: How to make a web app that works in IE 11?  I've written an article on this topic: https://medium.com/ringcentral-developers/create-a-ringcentral-web-app-that-works-in-ie-11-a5a165376193
