### ISSUE TITLE
Version 0.9.9 errors on console

### ISSUE THREAD

**Issue by ruleechen** [ringcentral/ringcentral-extensible#29]
Found some new errors on console log after upgrade to version 0.9.9
> TypeError: Cannot read property 'readyState' of undefined
> TypeError: Cannot read property 'close' of undefined
--- 
![image](https://user-images.githubusercontent.com/907369/118384227-09df0780-b637-11eb-938c-7d3315b4c4b7.png)
![image](https://user-images.githubusercontent.com/907369/118384309-a6a1a500-b637-11eb-913b-3e529b396756.png)
![image](https://user-images.githubusercontent.com/907369/118384235-1b281400-b637-11eb-9bfd-e18f5cd62cf1.png)
![image](https://user-images.githubusercontent.com/907369/118384246-398e0f80-b637-11eb-8386-dd7d1502beb5.png)
![image](https://user-images.githubusercontent.com/907369/118384295-8a9e0380-b637-11eb-8460-e856d47765aa.png)

**Comment by tylerlong** [comment]
Released 0.9.10
