### ISSUE TITLE
monorepo setup

### ISSUE THREAD

**Issue by u9520107** [ringcentral/ringcentral-extensible#3]
Currently the ability to use the default ringcentral sdk is built as an extension in this lib. I find the management of dependency packages a bit problematic. 

I'd suggest converting this into a monorepo setup and potentially releasing these extensions as separate packages under the same namespace.
This way these extension packages can have stronger control over defining dependencies.

**Comment by tylerlong** [comment]
I am good with the monorepo idea. Please post comments about the namespace and names. 

`@ringcentral-extensible/core`, `@ringcentral-extensible/websocket`, `@ringcentral-extensible/ringcentral` ... etc?

**Comment by tylerlong** [comment]
While I am searching the monorepo solution, I found this https://medium.com/@mattklein123/monorepos-please-dont-e9a279be011b

So maybe we could go with polyrepo instead

**Comment by u9520107** [comment]
Well... It is up to you really. I see arguments for and against monorepo all the time, but often enough they argue as if all projects must follow the same rules. That is, most supporters of monorepo will want to use monorepo for everything, and most non-supporters will never want to try and use monorepo.
Personally I think monorepo is just one of the forms of code management that is fitting for certain scenarios. And of course it does have its downsides.

Here are the reasons I think this project is fitting:
1. Relatively small code base: it will not become a giant pool of code that is too large to manage in one repo.
2. Inherent coupling: The extensions are by definition coupled with the core itself, changes to the core architecture or api could mean changes to the extensions. I think it is easier to manage them together and indeed leverage the "atomic" update provided by monorepo.
3. With a well implemented CI, publishing the core + extensions is still manageable, if not easier.

And some downsides:
1. You'll need to come up with a versioning rule for publishing. Our integrations monorepo is probably not a good example since a good number of packages we maintain there are never published. Perhaps use Babel as an example, and talk to @embbnux about this.
2.  Maybe some monorepo haters will complain?

**Comment by u9520107** [comment]
> I am good with the monorepo idea. Please post comments about the namespace and names.
> 
> `@ringcentral-extensible/core`, `@ringcentral-extensible/websocket`, `@ringcentral-extensible/ringcentral` ... etc?

Since @ringcentral-extensible is quite long already, I'd suggest making the second part shorter.
Perhaps `@ringcentral-extensible/ws`, `@ringcentral-extensible/rcsdk`?

**Comment by tylerlong** [comment]
Done. I chose `@rc-ex` as scope name.  Please read README file for more detail

**Comment by embbnux** [comment]
we can just use yarn workspace to instead lerna.js
