### ISSUE TITLE
WebSocket connection lost when recover with cached token

### ISSUE THREAD

**Issue by ruleechen** [ringcentral/ringcentral-extensible#39]
The feature of recover from cached token works well for single page. When we open two or more pages, each page try to recover from the cached token. The pages will try to launch their own websocket connection.

Then it comes to this issue: 

Each page will call the below api, but calling this api will disconnect other pages worksocket connection as my test. https://github.com/ringcentral/ringcentral-extensible/blob/76ae3d719dfdacc012db1be1bade7128f186d032/packages/extensions/ws/index.ts#L245

**Comment by tylerlong** [comment]
The root cause is: one `wsToken` can only establish one connection. If multiple tabs/pages share the same cached `wsToken`, existing connections will be disconnected upon new connections created.
