### ISSUE TITLE
WSG stops working after several minutes

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-extensible#6]

**Comment by ruleechen** [comment]
By watching on WebSocket `close` event. The connection will lost in 90 seconds.

**Comment by tylerlong** [comment]
Confirmed.  The lab env doesn't support heartbeat. Need to wait for lab env to update. Then add heartbeat feature to the SDK.

**Comment by tylerlong** [comment]
Fixed. As I tested no changes need to be done to the SDK. Because the WS lib handles heartbeat automatically.
