### ISSUE TITLE
Feature request: Reconnect after lost connection

### ISSUE THREAD

**Issue by ruleechen** [ringcentral/ringcentral-extensible#7]
The ws connection will lost such as when system resume from sleep. It's ok since the network is changed. But we need a mechanism to recover the connection when disconnected. It's better to have the mechanism integration with @rc-ex/ws module. Just like what we have in webphone sdk.

**Comment by tylerlong** [comment]
Have you tried the session recover feature: https://github.com/ringcentral/ringcentral-extensible/tree/master/packages/extensions/ws#session-recovery ?

**Comment by tylerlong** [comment]
Latest extension supports auto recover if ws connection is lost.
