### ISSUE TITLE
Many type errors found

### ISSUE THREAD

**Issue by ruleechen** [ringcentral/ringcentral-extensible#70]
Seems like there are many type errors in @rc-ex/ws project. Such as this one:

<img width="797" alt="image" src="https://user-images.githubusercontent.com/907369/221901083-283a1078-422a-4cbd-82b4-0bc96869e418.png">

**Comment by tylerlong** [comment]
Please  try "yarn reset && yarn compile"

Because `.../lib/` folder is empty or outdates before compilation.

**Comment by ruleechen** [comment]
Ok thanks. I'm closing this ticket.
