### ISSUE TITLE
Bad definition: SyncAddressBookParameters

### ISSUE THREAD

**Issue by u9520107** [ringcentral/ringcentral-extensible#8]
https://github.com/ringcentral/ringcentral-extensible/blob/c64fefca0fc680c008444d963d89fc9d157193ee/packages/core/definitions/SyncAddressBookParameters.ts#L5

This property should not be an array. It should only be 'FSync' | 'ISync'.
It seems the swagger definition is also wrong:
![image](https://user-images.githubusercontent.com/2562164/91631233-a8c0c680-ea0a-11ea-815b-2682d8f94846.png)

Also wrong in dwp's api reference:
![image](https://user-images.githubusercontent.com/2562164/91631261-e7ef1780-ea0a-11ea-9840-f7c288322378.png)

**Comment by tylerlong** [comment]
Confirmed that it is an issue. 

As a workaround, if you only specify one element in array, it should work.

SDK will update after swagger spec is fixed.

**Comment by tylerlong** [comment]
Fixed.

**Comment by tylerlong** [comment]
```
/restapi/v1.0/account/{accountId}/extension/{extensionId}/call-log-sync

/restapi/v1.0/account/{accountId}/call-log-sync

/restapi/v1.0/account/{accountId}/extension/{extensionId}/message-sync
```

Have similar issue.

**Comment by tylerlong** [comment]
All fixed.
