### ISSUE TITLE
Feedbacks about WS extension

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-extensible#9]
- the current implementation supports "wsc" section only for messages of the ConnectionDetails type. But it should support it for any incoming message types.
- the reconnect() is not executed automatically and has to be executed by clients after receiving Events.autoRecoverError. I suppose it is suitable to add some default logic in case of failed automatic recovery.
- recovery should not be retried for 60 seconds if there is no saved wsc token. From my point of view, It should fail asap and initiate reconnect().
- "autoRecovery" stops working after 60 seconds of client disconnection. And the new connection doesn't support auto-recovery. I could miss something but looks like this. Please, correct me if I'm wrong.
- there is a lack of something like Events.autoRecoverError for the case when we tried to recovered and received "recoveryState: Failed" in the ConnectionDetails message. Events.autoRecoverError could mean any problem including network problems. So it could be retried (e.g. 60 seconds) and doesn't require any special actions. But if the client received "recoveryState : Failed", it should not retry recovery and must reconnect, re-read all possibly stale info, and re-subscribe.

**Comment by tylerlong** [comment]
> the reconnect() is not executed automatically and has to be executed by clients after receiving Events.autoRecoverError. I suppose it is suitable to add some default logic in case of failed automatic recovery.

`reconnect()` is similar to `recover()` but it does not recover exiting subscriptions. `recover()` is auto invoked with `autoRecover = true`

`autoRecoverError` most likely means network error. It is not error from WSG.  So the SDK will auto retry. `setInterval` will not stop trying until you invoke `clearInterval`.


So the method `reconnect` is not that useful at all. I created it for SDK internal usage and debugging purpose.

**Comment by tylerlong** [comment]
> recovery should not be retried for 60 seconds if there is no saved wsc token. From my point of view, It should fail asap and initiate reconnect().

WSC token is saved together with the very first ConnectionDetail message. It is checked:

```ts
if (this.connectionDetails?.wsc?.token === undefined) {
      throw new Error('No existing session to recover');
    }
```

**Comment by tylerlong** [comment]
> "autoRecovery" stops working after 60 seconds of client disconnection. And the new connection doesn't support auto-recovery. I could miss something but looks like this. Please, correct me if I'm wrong.

`this.intervalHandle = setInterval(check, interval);` will not stop until you invoke `clearInterval`.  There is only one `clearInterval` in the code and it is followed by another `setInterval`. So it will never stop retrying(unless autoRecover is false).

**Comment by tylerlong** [comment]
> there is a lack of something like Events.autoRecoverFailed for the case when we tried to recovered and received "recoveryState: Failed" in the ConnectionDetails message. Events.autoRecoverError could mean any problem including network problems. So it could be retried (e.g. 60 seconds) and doesn't require any special actions. But if the client received "recoveryState : Failed", it should not retry recovery and must reconnect, re-read all possibly stale info, and re-subscribe.

By design, the SDK only issues `Events.autoRecoverFailed` if there is local network issue (or in rare cases WSG server is down). `recoveryState: Failed` is **internally handled and it is transparent** to the developer/user: 

```ts
if (
      recoverSession &&
      this.connectionDetails.body.recoveryState === 'Failed'
    ) {
      recoverSession = false;
    }

...

if (!recoverSession) {
        // create new subscription if don't recover existing one
        await subscription.subscribe();
      }
```

In such case `recover` equals `reconnect`: we will create brand new subscriptions. (Because old subscriptions recover failed).

**Comment by tylerlong** [comment]
> the current implementation supports "wsc" section only for messages of the ConnectionDetails type. But it should support it for any incoming message types.

I didn't know that other message types could provide "wsc" info. I will adjust the code.

**Comment by derbylock** [comment]
> > recovery should not be retried for 60 seconds if there is no saved wsc token. From my point of view, It should fail asap and initiate reconnect().
> 
> WSC token is saved together with the very first ConnectionDetails message. It is checked:
> 
> ```ts
> if (this.connectionDetails?.wsc?.token === undefined) {
>       throw new Error('No existing session to recover');
>     }
> ```

if wsc token is not set, the error will emit the Events.autoRecoverError and keep trying recover
```
          } catch (e) {
            interval += 10000;
            if (interval > 60000) {
              interval = 60000; // max interval 60 seconds
            }
            if (this.debugMode) {
              console.debug('Auto recover error:', e);
            }
            this.eventEmitter.emit(Events.autoRecoverError, e);
          }
```
but it should call the this.connect(false) instead because it will never receive wsc token in case of disconnect because of network issues.

The same logic should be used if recovery failed after number of seconds specified in the ConnectionDetails.recoveryTimeout field. In this case client should avoid recovery and simply initiate new connection.

**Comment by derbylock** [comment]
> If SDK can connect to WSG server, it will handle recoveryState === 'Failed' transparently and will not issue autoRecoverFailed.
I see your point but it means that client should have some event for the case to re-read current state. For example, a client shows user's presence. In case of failed recovery it should read current state of presence because it could changed for some users during the period of client unavailability. How could it be implemented?

**Comment by tylerlong** [comment]
> > the current implementation supports "wsc" section only for messages of the ConnectionDetails type. But it should support it for any incoming message types.
> 
> I didn't know that other message types could provide "wsc" info as well. I will adjust the code.

Fixed in latest version. Code snippet:

```ts
// listen for new wsc data
    this.ws.addEventListener('message', (event: WsgEvent) => {
      const [meta, body] = Utils.splitWsgData(event.data);
      if (
        meta.wsc &&
        (!this.wsc ||
          (meta.type === 'ConnectionDetails' && body.recoveryState) ||
          this.wsc.sequence < meta.wsc.sequence)
      ) {
        this.wsc = meta.wsc;
      }
    });
```

**Comment by tylerlong** [comment]
> > the reconnect() is not executed automatically and has to be executed by clients after receiving Events.autoRecoverError. I suppose it is suitable to add some default logic in case of failed automatic recovery.
> 
> `reconnect()` is similar to `recover()` but it does not recover exiting subscriptions(but create brand new subscriptions instead). `recover()` is auto invoked with `autoRecover = true`
> 
> `Events.autoRecoverError` most likely means network error(or WSG server is down). It is not error from WSG response body. So the SDK will auto retry. `setInterval` will not stop trying until you invoke `clearInterval`.
> 
> The method `reconnect` is not that useful at all. I created it for SDK internal usage and debugging purpose. `recover` is a "better" `reconnect` and it will keep retrying (if autoRecover = true) until network issue disappears.

In latest version I removed the `reconnect()` method. Because it was just an internal sugar method which equals to `connect(false)`.

External developers should only care about `recover()` method.

**Comment by tylerlong** [comment]
> > If SDK can connect to WSG server, it will handle recoveryState === 'Failed' transparently and will not issue autoRecoverFailed.
> 
> I see your point but it means that client should have some event for the case to re-read current state. For example, a client shows user's presence. In case of failed recovery it should read current state of presence because it could changed for some users during the period of client unavailability. How could it be implemented?

This is an issue even when recover successful.  Because recover cache might be full.  So developer just needs to listen to `Events.autoRecoverSuccess` and sync the state.

**Comment by tylerlong** [comment]
> > > recovery should not be retried for 60 seconds if there is no saved wsc token. From my point of view, It should fail asap and initiate reconnect().
> > 
> > 
> > WSC token is saved together with the very first ConnectionDetails message. It is checked:
> > ```ts
> > if (this.connectionDetails?.wsc?.token === undefined) {
> >       throw new Error('No existing session to recover');
> >     }
> > ```
> 
> if wsc token is not set, the error will emit the Events.autoRecoverError and keep trying recover
> 
> ```
>           } catch (e) {
>             interval += 10000;
>             if (interval > 60000) {
>               interval = 60000; // max interval 60 seconds
>             }
>             if (this.debugMode) {
>               console.debug('Auto recover error:', e);
>             }
>             this.eventEmitter.emit(Events.autoRecoverError, e);
>           }
> ```
> 
> but it should call the this.connect(false) instead because it will never receive wsc token in case of disconnect because of network issues.
> 
> The same logic should be used if recovery failed after number of seconds specified in the ConnectionDetails.recoveryTimeout field. In this case client should avoid recovery and simply initiate new connection.

Latest `recover` method has been updated to:

```ts
  async recover() {
    if (this.ws && this.ws.readyState === OPEN) {
      return;
    }
    if (!this.wsc || !this.wsc.token) {
      return await this.connect(false); // connect to WSG but do not recover
    }
    await this.connect(true); // connect to WSG and recover
  }
```
